### PR TITLE
Desktop integration fixes

### PR DESCRIPTION
**Pull request by keith-packard**
Rename directories to match application names.
Create xreversi and kdominos icons
Install icons to share/icons/hicolor/scalable/apps
Add .desktop files, install to share/applications

### CODE REVIEW

**Comment by BartMassey** [comment]
Maybe include the `debian/` directory in the repo so that I could try a test build + install?

**Comment by keith-packard** [comment]
You don't need to create a debian package, and it doesn't really help. Just do 'ninja install' and then run 'xdg-desktop-menu forceupdate' to get your menus reloaded.

**Comment by BartMassey** [comment]
Never mind, I was just screwing up.

Really blows out the Games menu. Maybe a submenu, at least for the solitaires?

**Comment by keith-packard** [comment]
> Really blows out the Games menu. Maybe a submenu, at least for the solitaires?

That's entirely up to the desktop environment; I've set all of the categories that are defined by the .desktop file specification...

**Comment by BartMassey** [comment]
Looks like there's a way to specify submenus in XDG, but it's convoluted enough to do what I want that I'm not going to think about it anymore.

**Pull request merged**
